# Generated by Django 3.2.5 on 2021-07-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('paragraph', models.TextField()),
                ('background', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Carouselcircle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(max_length=100)),
                ('paragraph1', models.TextField()),
                ('background1', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Carouselsquare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading2', models.CharField(max_length=100)),
                ('paragraph2', models.TextField()),
                ('background2', models.ImageField(upload_to='')),
            ],
        ),
    ]
